version: "2"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    #- forbidigo
    - funcorder
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - govet
    - iface
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - nestif
    - nilerr
    - nilnesserr
    - noctx
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - recvcheck
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - decorder
    - ginkgolinter
    - goheader
    - inamedparam
    - interfacebloat
    - prealloc
    - zerologlint
  settings:
    cyclop:
      max-complexity: 30
      package-average: 10.0

    errcheck:
      check-type-assertions: true

    exhaustive:
      check:
        - switch
        - map

    funcorder:
      struct-method: false

    funlen:
      lines: 100
      statements: 50

    gochecksumtype:
      default-signifies-exhaustive: false

    gocognit:
      min-complexity: 32

    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false

    govet:
      enable-all: true
      disable:
        - fieldalignment
      settings:
        shadow:
          strict: false

    inamedparam:
      skip-single-param: true

    nakedret:
      max-func-lines: 0

    perfsprint:
      strconcat: false

    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1016
        - -QF1008

    usetesting:
      os-temp-dir: true

  exclusions:
    warn-unused: false
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - source: 'TODO'
        linters: [ godot ]
      - path: '_test\.go'
        linters:
          - bodyclose
          - dupl
          - errcheck
          - funlen
          - goconst
          - noctx

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - localmodule
        - default
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
      no-lex-order: true
