builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

homebrew_casks:
  - name: pgmigrator
    binaries:
      - pgmigrator
    homepage: "https://github.com/vmkteam/pgmigrator"
    description: "Command-line tool for PostgreSQL migrations"
    repository:
      owner: vmkteam
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
